---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-subscribe-ansible"
      label: "Subscribe Ansible"
      solveButton: false
    - name: "02-inspect"
      label: "Inspect"
      solveButton: false
    - name: "03-swappiness"
      label: "Swappiness"
      solveButton: false
    - name: "04-new-role"
      label: "New Role"
      solveButton: false
    - name: "05-update-setting"
      label: "Update Setting"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
