Now that you have a working ansible playbook to standardize the
configuration of settings on your system, suppose that you realize one
of the settings needs to be changed.

Update the swappiness value in the playbook to be set to 10. This will
lower the kernel’s preference for utilizing swap space. You might make
this change because you are running a workload, like a database, that
benefits from having more data kept in memory rather than being swapped
out to the swap space.

[source,bash,run]
----
sed -ie 's/value: 20/value: 10/' soe.yml
----

In the above command, you used sed to make an inline edit to the soe.yml
file. You can verify that the change was correctly made by looking at
the playbook contents.

[source,bash,run]
----
cat soe.yml
----

Now that the settings have been updated, run the playbook again so that
the changes applied to the three systems.

[source,bash,run]
----
ansible-playbook soe.yml -i hosts.ini
----

After the playbook has completed, you can verify that the change has
been applied to the system.

[source,bash,run]
----
ssh client1 cat /proc/sys/vm/swappiness
----

This lab has focused on building a playbook using RHEL system roles to
generate a standard set of configuration for the system, then using that
playbook to make further changes to the system. Now that you have a
working playbook it would be trivial to change the hosts that it applies
to `+localhost+` to a set of systems on the network, like `+client1+`.
As a result, if updates needed to be made to parameters, like you did to
the swappiness setting, for the entire fleet of systems, you could
update the playbook, then execute it across the systems to propagate the
change.
